# Generated by Django 4.1.6 on 2023-02-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review", name="text", field=models.TextField(),
        ),
    ]
